### PR TITLE
Support `ltp_dequeue_outbound_segment()` and `ltp_handle_inbound_segment()`

### PR DESCRIPTION
**Pull request by pcrosemurgy**
## Description

Tested in Docker integration container in https://github.com/fprime-community/fprime-dtn.

Built with:
```
COPY lib/pyion /home/ptl/lib/pyion

ENV ION_HOME /home/ptl/lib/ion
ENV PYION_HOME /home/ptl/lib/pyion
ENV PYION_BP_VERSION BPv7
ENV LD_LIBRARY_PATH /home/ptl/lib/ion/.libs
RUN pip install --user /home/ptl/lib/pyion && \
    pip install --user numpy
```

`ltp_dequeue_outbound_segment()` requires a `with` clause. This allows for `sm_task_yield()` to internally (and unconditionally) be called when the dequeued segment has finished processing.

## Usage

```py
pyion.ltp.ltp_handle_inbound_segment(ltp_frame)
```

```py
with pyion.ltp.ltp_dequeue_outbound_segment(self.vspan) as ltp_frame:
    ...
```

### CODE REVIEW

**Comment by msancheznet** [comment]
@pcrosemurgy I have a few questions about this code before merging the pull request:

1. Why the need for using pthreads and related mutexes? Are we breaking compatibility for Windows users? Could we do threading instead at the Python level so that it is handled natively and has cross-support?
2. How does a user use ltp_init vs. ltp_attach and ltp_open? Previously the construct was always the same: (1) attach, (2) open, (3) close when done.

**Comment by pcrosemurgy** [comment]
@msancheznet Good catch, I think the pthread mutex was from an earlier iteration of mine and I forgot to take it out. I'll take this out and retest.

>How does a user use ltp_init vs. ltp_attach and ltp_open? Previously the construct was always the same: (1) attach, (2) open, (3) close when done.

Unfortunately, there's not really documentation for the LTP API outside of the `udplso.c` and `udplsi.c` implementations. LTP header files also do not have any comments explaining this API. I used the UDP LSO/LSI implementations as examples for dequeueing/enqueueing LTP segments into / out of ION. In these implementations all that's needed is an `ltpInit()` (`ltp_init()` in our Python wrapper).

I believe that `ltp_attach()` and `ltp_open()` are even more "internal" than `ltpInit()`. Looking at where they're used within ION hints at this I think:

The `ltpInit()` function uses:
```
stable:ion$ ag ltpInit -l
arch-rtems/pmqlsi.c
arch-rtems/pmqlso.c
ltp/udp/udplsi.c
ltp/udp/udplso.c
ltp/dccp/dccplsi.c
ltp/dccp/dccplso.c
ltp/library/libltpP.c
ltp/library/ltpP.h
ltp/utils/ltpadmin.c
ltp/daemon/ltpclock.c
ltp/daemon/ltpmeter.c
ltp/daemon/ltpdeliv.c
ltp/aos/aoslsi.c
ltp/aos/aoslso.c
contrib/ECLSAv2/ec/eclsa/extensions/HSLTP/hsltpProtocolAdapter_UP_ION_LTP.c
contrib/ECLSAv2/ec/eclsa/adapters/protocol/eclsaProtocolAdapter_UP_ION_LTP.c
```

The more "internal" LTP functions:
```
stable:ion$ ag ltp_open -l
ltp/sda/libsda.c
ltp/test/ltpcounter.c
ltp/include/ltp.h
ltp/library/libltp.c
ltp/doc/pod3/ltp.pod
bpv7/ltp/ltpcli.c
bpv6/ltp/ltpcli.c
stable:ion$ ag ltp_close -l
ltp/sda/libsda.c
ltp/test/ltpcounter.c
ltp/include/ltp.h
ltp/library/libltp.c
ltp/doc/pod3/ltp.pod
bpv7/ltp/ltpcli.c
bpv6/ltp/ltpcli.c
```

This shows an example of `ltp_init()` being used with the LTP enqueue/dequeue API: https://github.com/pcrosemurgy/fprime-gds-dtn/blob/50061f030769b87a395e46fd083a24cc5c0df0ea/src/fprime_gds/common/communication/updown.py#L327-L334

**Comment by msancheznet** [comment]
Thanks @pcrosemurgy. For reference, I seem to recall that the ION convention is that lower case functions (e.g., ltp_attach, ltp_open) are meant to be public APIs, and camel case functions (e.g., ltpInit) are meant to be private APIs. This is of course not documented anywhere that I know of :)

May Jay can shed some light as to the difference between ltpInit and the other functions.

**Comment by pcrosemurgy** [comment]
Latest commit removes the unused `_pthread_mutex.h`. I re-tested this with `fprime-dtn` and there are no regressions.

**Pull request merged**
